# Generated by Django 5.2.17 on 2026-08-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_add_slug_field'),
        ('universities', '0003_alter_university_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Опубліковано'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['is_approved', '-created_at'], name='programs_pr_is_appr_4a1a49_idx'),
        ),
    ]
