# Generated by Django 5.2.17 on 2026-08-19 12:37

from django.db import migrations, models

def migrate_data(apps, schema_editor):
    Program = apps.get_model('programs', 'Program')
    for program in Program.objects.exclude(user_university_text=''):
        text = program.user_university_text
        parts = text.split(' | ')
        for part in parts:
            if part.startswith('Faculty details: '):
                program.faculty_details = part[len('Faculty details: '):]
            elif part.startswith('Level details: '):
                program.level_details = part[len('Level details: '):]
        program.save(update_fields=['faculty_details', 'level_details'])


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0011_alter_program_created_at_alter_program_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='faculty_details',
            field=models.TextField(blank=True, default='', help_text="Коментар користувача про факультет (поле '+' у формі).", verbose_name='Деталі факультету (від користувача)'),
        ),
        migrations.AddField(
            model_name='program',
            name='level_details',
            field=models.TextField(blank=True, default='', help_text="Коментар користувача про рівень навчання (поле '+' у формі).", verbose_name='Деталі рівня навчання (від користувача)'),
        ),
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='program',
            name='user_university_text',
        ),
    ]
