# Generated by Django 5.2.17 on 2026-08-09 18:29

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_add_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=django_countries.fields.CountryField(db_index=True, max_length=2, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='university',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Опубліковано'),
        ),
    ]
