# Generated by Django 5.2.17 on 2026-08-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqitem',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Опубліковано'),
        ),
    ]
